export const USER_ABILITY = [
  {
    name: 'Branch Admin',
    role_enums: [2],
    abilities: [
      ['purchase-request', 'create'],
      ['purchase-request', 'read'],
      ['purchase-payment', 'create'],
      ['purchase-payment', 'read'],
      ['product', 'create'],
      ['product', 'read'],
      ['product-category', 'create'],
      ['product-category', 'read'],
    ],
  },
  {
    name: 'Admin Manager',
    role_enums: [3],
    abilities: [
      ['branch', 'create'],
      ['branch', 'read'],
      ['branch', 'update'],
      ['branch', 'delete'],
      ['staff', 'read'],
      ['staff', 'create'],
      ['staff', 'update'],
      ['currency', 'create'],
      ['currency', 'read'],
      ['currency', 'update'],
      ['currency', 'delete'],
      ['warehouse', 'create'],
      ['warehouse', 'read'],
      ['warehouse', 'update'],
      ['warehouse', 'delete'],
      ['supplier', 'create'],
      ['supplier', 'read'],
      ['supplier', 'update'],
      ['supplier', 'delete'],
      ['account-type', 'create'],
      ['account-type', 'read'],
      ['account-type', 'update'],
      ['account-type', 'delete'],
      ['purchase-plan', 'create'],
      ['purchase-plan', 'read'],
      ['purchase-plan', 'update'],
      ['purchase-plan', 'delete'],
      // ['purchase-request', 'create'],
      ['purchase-request', 'read'],
      ['purchase-request', 'update'],
      ['purchase-request', 'delete'],
      ['purchase-request', 'approval-request'],
      ['purchase-request', 'approve'],
      ['purchase-request', 'reject'],
      ['supplier-quotation', 'read'],
      ['supplier-quotation', 'create'],
      ['supplier-quotation', 'update'],
      ['supplier-quotation', 'delete'],
      ['supplier-quotation', 'receive'],
      ['supplier-quotation', 'cancel'],
      ['purchase-order', 'create'],
      ['purchase-order', 'read'],
      ['purchase-order', 'update'],
      ['purchase-order', 'delete'],
      // ['purchase-invoice', 'create'],
      ['purchase-invoice', 'read'],
      // ['purchase-invoice', 'update'],
      ['purchase-invoice', 'delete'],
      ['purchase-invoice', 'approval-request'],
      ['purchase-invoice', 'approve'],
      ['purchase-invoice', 'cancel'],
      ['purchase-invoice', 'download-pdf'],
      //  ['delivery-order', 'create'],
      //       ['delivery-order', 'read'],
      //       ['delivery-order', 'update'],
      //       ['delivery-order', 'delete'],
      //       ['delivery-order', 'complete'],
      //       ['delivery-order', 'cancel'],
      ['goods-receipt', 'create'],
      ['goods-receipt', 'read'],
      ['goods-receipt', 'update'],
      ['goods-receipt', 'delete'],
      ['goods-receipt', 'complete'],
      ['goods-receipt', 'cancel'],
      ['purchase-payment', 'create'],
      ['purchase-payment', 'read'],
      ['purchase-payment', 'update'],
      ['purchase-payment', 'delete'],
      ['purchase-payment', 'approve'],
      ['purchase-payment', 'cancel'],
      // ['purchase-return', 'create'],
      // ['purchase-return', 'read'],
      // ['purchase-return', 'update'],
      // ['purchase-return', 'delete'],
      ['product', 'create'],
      ['product', 'read'],
      ['product', 'update'],
      ['product', 'delete'],
      ['stock-movement', 'create'],
      ['stock-movement', 'read'],
      ['stock-movement', 'update'],
      ['stock-movement', 'delete'],
      ['product-category', 'create'],
      ['product-category', 'read'],
      ['product-category', 'update'],
      ['product-category', 'delete'],
      ['supplier-quotation', 'read'],
      ['supplier-quotation', 'create'],
      ['supplier-quotation', 'update'],
      ['supplier-quotation', 'delete'],
    ],
  },
  {
    name: 'supplier',
    role_enums: [7],
    abilities: [
      ['warehouse', 'read'],
      ['supplier-quotation', 'read'],
      ['supplier-quotation', 'update-price'],
      ['supplier-quotation', 'update'],
      ['product', 'read'],
      ['purchase-invoice', 'create'],
      ['purchase-invoice', 'read'],
      ['purchase-invoice', 'update'],
      ['purchase-order', 'read'],
      ['purchase-order', 'approve'],
    ],
  },
  {
    name: 'developer',
    role_enums: [0, 4],
    abilities: [
      ['warehouse', 'read'],
      ['warehouse', 'create'],
      ['warehouse', 'update'],
      ['warehouse', 'delete'],
      ['supplier-quotation', 'read'],
      ['supplier-quotation', 'create'],
      ['supplier-quotation', 'update'],
      ['supplier-quotation', 'delete'],
      ['supplier-quotation', 'receive'],
      ['supplier-quotation', 'cancel'],
      ['supplier', 'read'],
      ['supplier', 'create'],
      ['supplier', 'update'],
      ['supplier', 'delete'],
      ['stock-movement', 'read'],
      ['stock-movement', 'create'],
      ['staff', 'read'],
      ['staff', 'create'],
      ['staff', 'update'],
      ['service-invoice', 'read'],
      ['service-invoice', 'create'],
      ['service-invoice', 'update'],
      ['service-invoice', 'approval-request'],
      ['service-invoice', 'approval'],
      ['service-invoice', 'cancel'],
      ['branch', 'create'],
      ['branch', 'read'],
      ['branch', 'update'],
      ['branch', 'delete'],
      ['product', 'create'],
      ['product', 'read'],
      ['product', 'update'],
      ['product', 'delete'],
      ['product-category', 'create'],
      ['product-category', 'read'],
      ['product-category', 'update'],
      ['product-category', 'delete'],
      ['delivery-order', 'create'],
      // ['delivery-order', 'read'],
      // ['delivery-order', 'update'],
      // ['delivery-order', 'delete'],
      // ['delivery-order', 'complete'],
      // ['delivery-order', 'cancel'],
      ['goods-receipt', 'create'],
      ['goods-receipt', 'read'],
      ['goods-receipt', 'update'],
      ['goods-receipt', 'delete'],
      ['goods-receipt', 'complete'],
      ['goods-receipt', 'cancel'],
      ['purchase-invoice', 'create'],
      ['purchase-invoice', 'read'],
      ['purchase-invoice', 'update'],
      ['purchase-invoice', 'delete'],
      ['purchase-invoice', 'approval-request'],
      ['purchase-invoice', 'approve'],
      ['purchase-invoice', 'cancel'],
      ['purchase-invoice', 'download-pdf'],
      ['purchase-order', 'create'],
      ['purchase-order', 'read'],
      ['purchase-order', 'update'],
      ['purchase-order', 'delete'],
      ['purchase-order', 'approve'],
      ['purchase-order', 'cancel'],
      ['purchase-payment', 'create'],
      ['purchase-payment', 'read'],
      ['purchase-payment', 'update'],
      ['purchase-payment', 'delete'],
      ['purchase-payment', 'approve'],
      ['purchase-payment', 'cancel'],
      ['purchase-plan', 'create'],
      ['purchase-plan', 'read'],
      ['purchase-plan', 'update'],
      ['purchase-plan', 'delete'],
      ['purchase-request', 'create'],
      ['purchase-request', 'read'],
      ['purchase-request', 'update'],
      ['purchase-request', 'delete'],
    ],
  },
];
